version: 2
jobs:
    build:
        docker:
            - image: circleci/node:10
        steps:
            - checkout
            - restore_cache: # special step to restore the dependency cache
                  name: Restore Yarn Package Cache
                  keys:
                      - yarn-packages-{{ checksum "yarn.lock" }}
            - run:
                  name: Setup Yarn Dependencies #install all the dependencies
                  command: yarn install --frozen-lockfile
            - save_cache: #saves a cache of the installed dependencies
                  name: Save Yarn Package Cache
                  key: yarn-packages-{{ checksum "yarn.lock" }}
                  paths:
                      - ~/.cache/yarn
            - run:
                  name: Lint checks
                  command: yarn run lint
            - run:
                  name: Tests
                  command: yarn run test-once --maxWorkers 2
            - run:
                  name: Coveralls
                  command: COVERALLS_REPO_TOKEN=${COVERALLS_REPO_TOKEN} && yarn run coveralls
